# Analysis of Model judgments for robustness to question variation

In [1]:
import numpy as np
import pandas as pd

import output_processing as op

/Users/abhishekp/miniconda3/envs/prej_prompt/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
model_list = [
    # Main set of models with instruct divide and size variety
    "meta-llama/Llama-3.2-1B",
    "meta-llama/Llama-3.2-1B-Instruct",
    "meta-llama/Llama-3.2-3B",
    "meta-llama/Llama-3.2-3B-Instruct",
    "meta-llama/Llama-3.1-8B",
    "meta-llama/Llama-3.1-8B-Instruct",
    "meta-llama/Llama-3.1-70B",
    "meta-llama/Llama-3.3-70B-Instruct",
    # Small reference model - would allow for pretraining variation
    "gpt2-medium",
    # Other open models
    "allenai/OLMo-2-1124-7B",
    "allenai/OLMo-2-1124-7B-Instruct",
    "mistralai/Ministral-8B-Instruct-2410",
    "google/gemma-7b",
    "google/gemma-7b-it",
    # Large platform model
    "openai-gpt-4",
]

def read_and_organize_model_results(model_name):
    model_results = pd.read_csv(f"runs/runs-42_07_16/{model_name}-results.csv")
    # model_results.replace([0.0], -65504, inplace=True)
    model_results = op.organize_distribution(model_results)
    model_results["model_name"] = model_name.split("/")[-1]
    model_results.loc[model_results["Covered"] == True, "Judgment"] = "Covered"
    model_results.loc[model_results["Covered"] == True, "Judgment_prob"] = model_results["Covered_prob"]
    model_results.loc[model_results["NotCovered"] == True, "Judgment"] = "NotCovered"
    model_results.loc[model_results["NotCovered"] == True, "Judgment_prob"] = model_results["NotCovered_prob"]
    return model_results

In [3]:
# TODO organize the output for better clarity
combined_results = [read_and_organize_model_results(model_name) for model_name in model_list]
combined_df = pd.concat(combined_results).reset_index()
combined_df.loc[:, "item"] = combined_df["title"] + combined_df["version"]
combined_df.shape

(18630, 28)

In [4]:
def update_probs_gt_1():
    covered_gt_1_mask = combined_df["Covered_prob"] >= 1
    print(np.sum(covered_gt_1_mask))
    combined_df.loc[covered_gt_1_mask, ["NotCovered_prob", "Other_prob"]] = 0
    combined_df.loc[covered_gt_1_mask, "Covered_prob"] = 1
    print(np.sum(combined_df["Covered_prob"] > 1))

    notcovered_gt_1_mask = combined_df["NotCovered_prob"] >= 1
    print(np.sum(notcovered_gt_1_mask))
    combined_df.loc[notcovered_gt_1_mask, "NotCovered_prob"] = 1
    combined_df.loc[notcovered_gt_1_mask, ["Covered_prob", "Other_prob"]] = 0
    print(np.sum(combined_df["NotCovered_prob"] > 1))
    
update_probs_gt_1()

108
0
92
0

In [5]:
sorted(combined_df[["Covered_prob", "NotCovered_prob", "Other_prob"]].apply(np.sum, axis=1).value_counts().index.unique())

[0.9999999999999999, 1.0]

In [6]:
# Print summary of the experimental results
print(combined_df.model_name.unique())

['Llama-3.2-1B' 'Llama-3.2-1B-Instruct' 'Llama-3.2-3B'
 'Llama-3.2-3B-Instruct' 'Llama-3.1-8B' 'Llama-3.1-8B-Instruct'
 'Llama-3.1-70B' 'Llama-3.3-70B-Instruct' 'gpt2-medium' 'OLMo-2-1124-7B'
 'OLMo-2-1124-7B-Instruct' 'Ministral-8B-Instruct-2410' 'gemma-7b'
 'gemma-7b-it' 'openai-gpt-4']

In [7]:
# Looking at one of the result samples
combined_df.sample()

,index,title,prompt_type,prompt,version,output,output_text,cum_logprob,YES_probs,Yes_probs,...,Covered_prob,NotCovered_prob,Covered,NotCovered,Other_prob,entropy,model_name,Judgment,Judgment_prob,item
15294,390,Vehicle Theft I,negation,Gisele's car insurance policy includes coverag...,unambiguous_uncovered,yes,"yes.\nThe term ""audio equipment"" is not defin...",NaN,0.052254,0.326103,...,0.326103,0.310448,True,False,0.363449,1.096408,gemma-7b,Covered,0.326103,Vehicle Theft Iunambiguous_uncovered

## Prepare the table with Categorical counts and Distributional Spread

In [8]:
# Categorical Counts for Yes/No question variant
question_variant_mask = combined_df["prompt_type"] == "yes_or_no"
yes_or_no_df = combined_df[question_variant_mask]
count_labels = yes_or_no_df.groupby('model_name', as_index=False, sort=False).aggregate(
    {
        'Covered': 'sum',
        'NotCovered': 'sum',
    }
)
count_labels = count_labels.rename({'model_name' : 'Model'}, axis=1)
count_labels

                         Model  Covered  NotCovered
0                 Llama-3.2-1B      138           0
1        Llama-3.2-1B-Instruct      138           0
2                 Llama-3.2-3B      127          11
3        Llama-3.2-3B-Instruct       53          85
4                 Llama-3.1-8B       80          58
5        Llama-3.1-8B-Instruct        0         138
6                Llama-3.1-70B       28         110
7       Llama-3.3-70B-Instruct       59          79
8                  gpt2-medium        5         133
9               OLMo-2-1124-7B       70          68
10     OLMo-2-1124-7B-Instruct       53          85
11  Ministral-8B-Instruct-2410       75          63
12                    gemma-7b       39          99
13                 gemma-7b-it      131           7
14                openai-gpt-4       77          61

In [9]:
# Latex table just for categorical counts
count_labels.to_latex("reports/yes_or_no_categorical_counts.tex", index=False, float_format="%.2f")

In [10]:
# Distributional spread for Yes/No question variant
question_variant_mask = combined_df["prompt_type"] == "yes_or_no"
yes_or_no_df = combined_df[question_variant_mask]

# Util function
yes_or_no_judgement_range = yes_or_no_df[['model_name', 'Covered_prob', 'NotCovered_prob']].melt(id_vars='model_name', value_vars=['Covered_prob', 'NotCovered_prob']).groupby('model_name', as_index=False).agg(
    Min = pd.NamedAgg('value', lambda x: np.round(np.min(x), 3)),
    Max = pd.NamedAgg('value', lambda x: np.round(np.max(x), 3)),
    ).rename({"model_name": "Model"}, axis=1)

yes_or_no_judgement_range

                         Model    Min    Max
0                Llama-3.1-70B  0.209  0.476
1                 Llama-3.1-8B  0.138  0.367
2        Llama-3.1-8B-Instruct  0.110  0.742
3                 Llama-3.2-1B  0.064  0.291
4        Llama-3.2-1B-Instruct  0.151  0.592
5                 Llama-3.2-3B  0.093  0.517
6        Llama-3.2-3B-Instruct  0.159  0.690
7       Llama-3.3-70B-Instruct  0.022  0.849
8   Ministral-8B-Instruct-2410  0.211  0.595
9               OLMo-2-1124-7B  0.190  0.564
10     OLMo-2-1124-7B-Instruct  0.001  0.991
11                    gemma-7b  0.191  0.490
12                 gemma-7b-it  0.000  1.000
13                 gpt2-medium  0.129  0.308
14                openai-gpt-4  0.000  1.000

In [11]:
# Separate latex table for yes_or_no judgement range
yes_or_no_judgement_range.to_latex("reports/yes_or_no_distributional_spread.tex", index=False, float_format="%.2f")

In [12]:
# Combined table
# Merge the two tables
yes_or_no_table = pd.concat([count_labels.set_index('Model'), yes_or_no_judgement_range.set_index('Model')], axis=1, join='inner')
yes_or_no_table

                            Covered  NotCovered    Min    Max
Model
Llama-3.2-1B                    138           0  0.064  0.291
Llama-3.2-1B-Instruct           138           0  0.151  0.592
Llama-3.2-3B                    127          11  0.093  0.517
Llama-3.2-3B-Instruct            53          85  0.159  0.690
Llama-3.1-8B                     80          58  0.138  0.367
Llama-3.1-8B-Instruct             0         138  0.110  0.742
Llama-3.1-70B                    28         110  0.209  0.476
Llama-3.3-70B-Instruct           59          79  0.022  0.849
gpt2-medium                       5         133  0.129  0.308
OLMo-2-1124-7B                   70          68  0.190  0.564
OLMo-2-1124-7B-Instruct          53          85  0.001  0.991
Ministral-8B-Instruct-2410       75          63  0.211  0.595
gemma-7b                         39          99  0.191  0.490
gemma-7b-it                     131           7  0.000  1.000
openai-gpt-4                     77          61  0.000  1.000

In [13]:
yes_or_no_table.to_latex("reports/yes_or_no_table.tex", index=True, float_format="%.2f")

## Prepare the majority votes frequency table

In [14]:
# Calculate the majority votes
majority_vote_by_model = combined_df.groupby(['title', 'version', 'model_name'], as_index=False, sort=False).aggregate(
     {
        'Covered': 'sum',
        'NotCovered': 'sum',
    }
)
majority_vote_by_model.loc[:, "majority_count"] = majority_vote_by_model[['Covered', 'NotCovered']].max(axis=1)
majority_vote_by_model.shape
majority_vote_table_df = majority_vote_by_model[["model_name", "majority_count"]].value_counts().reset_index(name="Frequency")\
.pivot_table(columns =['majority_count'], index="model_name", aggfunc="sum", margins=True)\

majority_vote_table_df.replace(np.nan, 0, inplace=True)
# Remove the "All" from columns and rows
majority_vote_table_df = majority_vote_table_df.drop(["All"], axis=0)
majority_vote_table_df = majority_vote_table_df.drop([("Frequency", "All")], axis=1)

majority_vote_table_df = majority_vote_table_df.rename({'model_name': 'Model', 'majority_count': 'Majority Count'})
majority_vote_table_df.index = majority_vote_table_df.index.rename('Model')
majority_vote_table_df.columns.names = [None, 'Majority Count']
majority_vote_table_df

                           Frequency
Majority Count                     5     6     7     8    9
Model
Llama-3.1-70B                   33.0  68.0  36.0   1.0  0.0
Llama-3.1-8B                    40.0  52.0  46.0   0.0  0.0
Llama-3.1-8B-Instruct            6.0  39.0  59.0  31.0  3.0
Llama-3.2-1B                    12.0  57.0  69.0   0.0  0.0
Llama-3.2-1B-Instruct          129.0   9.0   0.0   0.0  0.0
Llama-3.2-3B                    95.0  40.0   3.0   0.0  0.0
Llama-3.2-3B-Instruct           75.0  48.0  15.0   0.0  0.0
Llama-3.3-70B-Instruct          25.0  33.0  78.0   2.0  0.0
Ministral-8B-Instruct-2410      24.0  65.0  30.0  18.0  1.0
OLMo-2-1124-7B                  46.0  65.0  20.0   7.0  0.0
OLMo-2-1124-7B-Instruct         51.0  57.0  30.0   0.0  0.0
gemma-7b                        44.0  58.0  29.0   7.0  0.0
gemma-7b-it                      9.0  31.0  79.0  19.0  0.0
gpt2-medium                     50.0  83.0   5.0   0.0  0.0
openai-gpt-4                     4.0   9.0  57.0  63.0  5.0

In [15]:
majority_vote_table_df.to_latex("reports/majority-votes-freq-table.tex", float_format="%.0f")

In [16]:
# Calculate the majority votes
top_4_minority_variants =  ["disagreement", "agreement_negation", "disagreement_negation", "options"]
selected_df = combined_df[~combined_df["prompt_type"].isin(top_4_minority_variants)]
print(combined_df.shape, selected_df.shape)
limited_majority_vote_by_model = selected_df.groupby(['title', 'version', 'model_name'], as_index=False, sort=False).aggregate(
     {
        'Covered': 'sum',
        'NotCovered': 'sum',
    }
)
limited_majority_vote_by_model.loc[:, "majority_count"] = limited_majority_vote_by_model[['Covered', 'NotCovered']].max(axis=1)
limited_majority_vote_by_model.shape
limited_majority_vote_by_model_df = limited_majority_vote_by_model[["model_name", "majority_count"]].value_counts().reset_index(name="Frequency")\
.pivot_table(columns =['majority_count'], index="model_name", aggfunc="sum", margins=True)\

limited_majority_vote_by_model_df.replace(np.nan, 0, inplace=True)
# Remove the "All" from columns and rows
# limited_majority_vote_by_model_df = limited_majority_vote_by_model_df.drop(["All"], axis=0)
limited_majority_vote_by_model_df = limited_majority_vote_by_model_df.drop([("Frequency", "All")], axis=1)

limited_majority_vote_by_model_df = limited_majority_vote_by_model_df.rename({'model_name': 'Model', 'majority_count': 'Majority Count'})
limited_majority_vote_by_model_df.index = limited_majority_vote_by_model_df.index.rename('Model')
limited_majority_vote_by_model_df.columns.names = [None, 'Majority Count']
limited_majority_vote_by_model_df

(18630, 28) (10350, 28)

                           Frequency
Majority Count                     3      4      5
Model
Llama-3.1-70B                   22.0   21.0   95.0
Llama-3.1-8B                    33.0   43.0   62.0
Llama-3.1-8B-Instruct           13.0   98.0   27.0
Llama-3.2-1B                     4.0   25.0  109.0
Llama-3.2-1B-Instruct           13.0  125.0    0.0
Llama-3.2-3B                    11.0  113.0   14.0
Llama-3.2-3B-Instruct           57.0   48.0   33.0
Llama-3.3-70B-Instruct          24.0   93.0   21.0
Ministral-8B-Instruct-2410      16.0   67.0   55.0
OLMo-2-1124-7B                  71.0   26.0   41.0
OLMo-2-1124-7B-Instruct         36.0   77.0   25.0
gemma-7b                        45.0   50.0   43.0
gemma-7b-it                      9.0   47.0   82.0
gpt2-medium                     67.0   71.0    0.0
openai-gpt-4                     5.0   41.0   92.0
All                            426.0  945.0  699.0

In [17]:
limited_majority_vote_by_model_df.to_latex("reports/majority-votes-only-5-freq-table.tex", float_format="%.0f")

## Minority responses

In [18]:
# Minority responses
combined_df.loc[combined_df.Covered == True, "judgment"] = "Covered"
combined_df.loc[combined_df.NotCovered == True, "judgment"] = "Not Covered"
majority_vote_by_model.loc[:, "majority"] = majority_vote_by_model.apply(lambda x: "Covered" if x.Covered >= x.NotCovered else "Not Covered",  axis=1)
combined_df.loc[:, "in_minority"]= False
for index, row in majority_vote_by_model.iterrows():
    item_model_mask = (combined_df["title"] == row.title) & (combined_df["version"] == row.version) & (combined_df["model_name"] == row.model_name)
    in_minority_mask = combined_df["judgment"]!= row.majority
    combined_df.loc[item_model_mask & in_minority_mask, "in_minority"] = True

combined_df.in_minority.sum(), combined_df.shape[0]

## Minority responses by question variants for each model

(5974, 18630)

In [19]:
minority_responses = combined_df[combined_df.in_minority == True]

In [20]:
minority_pivot = minority_responses[["model_name", "prompt_type"]].value_counts().reset_index().pivot_table(index="model_name", columns="prompt_type")
minority_pivot.replace(np.nan, 0, inplace=True)
minority_pivot

                               count                                  \
prompt_type                agreement agreement_negation disagreement
model_name
Llama-3.1-70B                   15.0               98.0         71.0
Llama-3.1-8B                    21.0              101.0        112.0
Llama-3.1-8B-Instruct            5.0               29.0         58.0
Llama-3.2-1B                     0.0              138.0        138.0
Llama-3.2-1B-Instruct           13.0              125.0        125.0
Llama-3.2-3B                   123.0              137.0        104.0
Llama-3.2-3B-Instruct           47.0               74.0         74.0
Llama-3.3-70B-Instruct          14.0               57.0         46.0
Ministral-8B-Instruct-2410      10.0               48.0         75.0
OLMo-2-1124-7B                  68.0               63.0         65.0
OLMo-2-1124-7B-Instruct         34.0               68.0        106.0
gemma-7b                        17.0               64.0         88.0
gemma-7b-it                      7.0                5.0        127.0
gpt2-medium                    124.0               14.0         14.0
openai-gpt-4                     3.0               24.0         53.0

                                                                             \
prompt_type                disagreement_negation negation no_or_yes options
model_name
Llama-3.1-70B                               73.0     14.0      14.0    96.0
Llama-3.1-8B                                37.0     29.0      16.0    33.0
Llama-3.1-8B-Instruct                       74.0     32.0       1.0     1.0
Llama-3.2-1B                                 0.0      0.0      16.0    48.0
Llama-3.2-1B-Instruct                       13.0      0.0     125.0   116.0
Llama-3.2-3B                                 2.0      1.0       1.0   127.0
Llama-3.2-3B-Instruct                       64.0     41.0      29.0    65.0
Llama-3.3-70B-Instruct                      89.0     99.0      11.0    19.0
Ministral-8B-Instruct-2410                  70.0     61.0       7.0    72.0
OLMo-2-1124-7B                              61.0     27.0      21.0    44.0
OLMo-2-1124-7B-Instruct                     70.0     48.0       9.0    26.0
gemma-7b                                    53.0     32.0      14.0    63.0
gemma-7b-it                                101.0     23.0       5.0     5.0
gpt2-medium                                124.0     41.0       4.0    90.0
openai-gpt-4                                87.0     41.0       2.0     4.0


prompt_type                options_flipped yes_or_no
model_name
Llama-3.1-70B                         17.0      11.0
Llama-3.1-8B                          30.0      29.0
Llama-3.1-8B-Instruct                 89.0       1.0
Llama-3.2-1B                          17.0       0.0
Llama-3.2-1B-Instruct                 13.0      13.0
Llama-3.2-3B                           1.0      10.0
Llama-3.2-3B-Instruct                 57.0      23.0
Llama-3.3-70B-Instruct                18.0       4.0
Ministral-8B-Instruct-2410            17.0       9.0
OLMo-2-1124-7B                        66.0      11.0
OLMo-2-1124-7B-Instruct               57.0      17.0
gemma-7b                              38.0      46.0
gemma-7b-it                           31.0       2.0
gpt2-medium                           39.0       9.0
openai-gpt-4                           3.0       3.0

## Minority responses by question variants

In [21]:
# Minority responses
combined_df.loc[combined_df.Covered == True, "judgment"] = "Covered"
combined_df.loc[combined_df.NotCovered == True, "judgment"] = "Not Covered"
majority_vote_by_model.loc[:, "majority"] = majority_vote_by_model.apply(lambda x: "Covered" if x.Covered >= x.NotCovered else "Not Covered",  axis=1)
combined_df.loc[:, "in_minority"]= False
for index, row in majority_vote_by_model.iterrows():
    item_model_mask = (combined_df["title"] == row.title) & (combined_df["version"] == row.version) & (combined_df["model_name"] == row.model_name)
    in_minority_mask = combined_df["judgment"]!= row.majority
    combined_df.loc[item_model_mask & in_minority_mask, "in_minority"] = True

combined_df.in_minority.sum(), combined_df.shape[0]

(5974, 18630)

In [22]:
minority_responses = combined_df[combined_df.in_minority == True]
minority_responses[["prompt_type"]].value_counts().reset_index()

             prompt_type  count
0           disagreement   1256
1     agreement_negation   1045
2  disagreement_negation    918
3                options    809
4              agreement    501
5        options_flipped    493
6               negation    489
7              no_or_yes    275
8              yes_or_no    188

In [23]:
(minority_responses[["prompt_type"]].value_counts()/minority_responses.shape[0]).reset_index()

             prompt_type     count
0           disagreement  0.210244
1     agreement_negation  0.174925
2  disagreement_negation  0.153666
3                options  0.135420
4              agreement  0.083863
5        options_flipped  0.082524
6               negation  0.081855
7              no_or_yes  0.046033
8              yes_or_no  0.031470

In [24]:
minority_responses = minority_responses.replace(
    {
        "agreement" : "Agr.",
        "disagreement" : "Disagr.",
        "yes_or_no": "Y/N",
        "agreement_negation": "Agr. w/ Neg.", 
        "no_or_yes": "N/Y", 
        "disagreement_negation": "Disagr. w/ Neg.", 
        "options_flipped": "Options F.", 
        "options": "Options", 
        "negation": "Negation",
    }
)
minority_counts = minority_responses[["prompt_type"]].value_counts().reset_index().set_index("prompt_type")
minority_counts.columns = ['Count']
minority_props = (minority_counts/minority_responses.shape[0]).reset_index().set_index("prompt_type")
minority_props.columns = ['Proportion']
minority_merged_table = pd.concat([minority_counts, minority_props], axis=1, join='inner')
minority_merged_table.index = minority_merged_table.index.rename('Variant')
minority_merged_table

                 Count  Proportion
Variant
Disagr.           1256    0.210244
Agr. w/ Neg.      1045    0.174925
Disagr. w/ Neg.    918    0.153666
Options            809    0.135420
Agr.               501    0.083863
Options F.         493    0.082524
Negation           489    0.081855
N/Y                275    0.046033
Y/N                188    0.031470

In [25]:
minority_merged_table.to_latex("reports/minority-variants-counts-proportion.tex", index=True, float_format="%.2f")

In [26]:
# minority_responses
top_3_minority_variants =  ["Disagr.", "Agr. w/ Neg.", "Disagr. w/ Neg."]
non_top_3_minority_responses = minority_responses[~minority_responses.prompt_type.isin(top_3_minority_variants)]
non_top_3_minority_pivot = non_top_3_minority_responses[["model_name", "prompt_type"]].value_counts().reset_index().pivot_table(index="model_name", columns="prompt_type")
non_top_3_minority_pivot.replace(np.nan, 0, inplace=True)
non_top_3_minority_pivot

                            count
prompt_type                  Agr.    N/Y Negation Options Options F.   Y/N
model_name
Llama-3.1-70B                15.0   14.0     14.0    96.0       17.0  11.0
Llama-3.1-8B                 21.0   16.0     29.0    33.0       30.0  29.0
Llama-3.1-8B-Instruct         5.0    1.0     32.0     1.0       89.0   1.0
Llama-3.2-1B                  0.0   16.0      0.0    48.0       17.0   0.0
Llama-3.2-1B-Instruct        13.0  125.0      0.0   116.0       13.0  13.0
Llama-3.2-3B                123.0    1.0      1.0   127.0        1.0  10.0
Llama-3.2-3B-Instruct        47.0   29.0     41.0    65.0       57.0  23.0
Llama-3.3-70B-Instruct       14.0   11.0     99.0    19.0       18.0   4.0
Ministral-8B-Instruct-2410   10.0    7.0     61.0    72.0       17.0   9.0
OLMo-2-1124-7B               68.0   21.0     27.0    44.0       66.0  11.0
OLMo-2-1124-7B-Instruct      34.0    9.0     48.0    26.0       57.0  17.0
gemma-7b                     17.0   14.0     32.0    63.0       38.0  46.0
gemma-7b-it                   7.0    5.0     23.0     5.0       31.0   2.0
gpt2-medium                 124.0    4.0     41.0    90.0       39.0   9.0
openai-gpt-4                  3.0    2.0     41.0     4.0        3.0   3.0

In [27]:
pd.concat([minority_counts, minority_props], axis=1, join='inner').columns

Index(['Count', 'Proportion'], dtype='object')

## Make the table for Jensen-Shannon Distance for non Yes/No question variant

In [28]:
lt_0_other_prob = combined_df["Other_prob"] < 0
print(np.sum(lt_0_other_prob))
combined_df.loc[lt_0_other_prob, "Other_prob"] = 0
divergences = op.calculate_relative_measures(combined_df)
divergences.sample()

167

,title,version,model_name,prompt_type,js_dist,kl_div
15255,Vehicle Damage V,unambiguous_covered,gemma-7b-it,options_flipped,0.603733,1.319403

In [44]:
divergences.groupby(['model_name', 'prompt_type'], as_index=False, sort=False).aggregate(
    Mean = pd.NamedAgg('js_dist', "mean"),
    Std = pd.NamedAgg('js_dist', "std")
).groupby(['model_name'], as_index=False, sort=True).apply(lambda x: x)

/var/folders/0m/231b9j890r542zfr6djkqlz40000gp/T/ipykernel_32335/2038001485.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ).groupby(['model_name'], as_index=False, sort=True).apply(lambda x: x)

           model_name            prompt_type      Mean       Std
0  48   Llama-3.1-70B              no_or_yes  0.033416  0.014150
   49   Llama-3.1-70B               negation  0.050868  0.015951
   50   Llama-3.1-70B              agreement  0.026807  0.014100
   51   Llama-3.1-70B     agreement_negation  0.052453  0.028438
   52   Llama-3.1-70B           disagreement  0.055269  0.025534
...               ...                    ...       ...       ...
14 115   openai-gpt-4     agreement_negation  0.152546  0.239518
   116   openai-gpt-4           disagreement  0.306316  0.308616
   117   openai-gpt-4  disagreement_negation  0.564847  0.304594
   118   openai-gpt-4                options  0.056860  0.118123
   119   openai-gpt-4        options_flipped  0.048326  0.105593

[120 rows x 4 columns]

In [31]:
max_distance_variant_for_model = divergences.groupby(['model_name', 'prompt_type'], as_index=False, sort=False).aggregate(
    Mean = pd.NamedAgg('js_dist', "mean"),
    Std = pd.NamedAgg('js_dist', "std")
).groupby(['model_name'], as_index=False, sort=False).apply(lambda x: x.loc[x["Mean"].idxmax(), :])
max_distance_variant_for_model = max_distance_variant_for_model.rename({'model_name' : 'Model', 'prompt_type': 'Variant'}, axis=1)
max_distance_variant_for_model = max_distance_variant_for_model.replace(
    {
        "agreement_negation": "Agr. w/ Neg.", 
        "no_or_yes": "N/Y", 
        "disagreement_negation": "Disagr. w/ Neg.", 
        "options_flipped": "Options F.", 
        "options": "Options", 
        "negation": "Negation",
    }
)
max_distance_variant_for_model

/var/folders/0m/231b9j890r542zfr6djkqlz40000gp/T/ipykernel_32335/4163965735.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ).groupby(['model_name'], as_index=False, sort=False).apply(lambda x: x.loc[x["Mean"].idxmax(), :])

                         Model          Variant      Mean       Std
0                 Llama-3.2-1B          Options  0.283329  0.048375
1        Llama-3.2-1B-Instruct       Options F.  0.317063  0.039822
2                 Llama-3.2-3B     Agr. w/ Neg.  0.190244  0.056740
3        Llama-3.2-3B-Instruct       Options F.  0.219421  0.073405
4                 Llama-3.1-8B       Options F.  0.151213  0.035114
5        Llama-3.1-8B-Instruct  Disagr. w/ Neg.  0.177796  0.062130
6                Llama-3.1-70B          Options  0.087815  0.040088
7       Llama-3.3-70B-Instruct         Negation  0.335640  0.168559
8                  gpt2-medium  Disagr. w/ Neg.  0.166641  0.019487
9               OLMo-2-1124-7B  Disagr. w/ Neg.  0.373452  0.049581
10     OLMo-2-1124-7B-Instruct     Agr. w/ Neg.  0.479822  0.233770
11  Ministral-8B-Instruct-2410          Options  0.164534  0.043486
12                    gemma-7b  Disagr. w/ Neg.  0.079808  0.030844
13                 gemma-7b-it          Options  0.779220  0.039983
14                openai-gpt-4  Disagr. w/ Neg.  0.564847  0.304594

In [33]:
max_distance_variant_for_model.to_latex("reports/robustness-prompt-type-distance.tex", float_format="%0.2f", index=False)

In [48]:
top_3_minority_variants =  ["disagreement", "agreement_negation", "disagreement_negation"]
divergences_non_top3 = divergences[~divergences.prompt_type.isin(top_3_minority_variants)]
limited_distance_variant_for_model = divergences_non_top3.groupby(['model_name', 'prompt_type'], as_index=False, sort=False).aggregate(
    Mean = pd.NamedAgg('js_dist', "mean"),
    Std = pd.NamedAgg('js_dist', "std")
).groupby(['model_name'], as_index=False, sort=False).apply(lambda x: x.loc[x["Mean"].idxmax(), :])
limited_distance_variant_for_model = limited_distance_variant_for_model.rename({'model_name' : 'Model', 'prompt_type': 'Variant'}, axis=1)
limited_distance_variant_for_model = limited_distance_variant_for_model.replace(
    {
        "agreement_negation": "Agr. w/ Neg.", 
        "no_or_yes": "N/Y", 
        "disagreement_negation": "Disagr. w/ Neg.", 
        "options_flipped": "Options F.", 
        "options": "Options", 
        "negation": "Negation",
    }
)
limited_distance_variant_for_model

/var/folders/0m/231b9j890r542zfr6djkqlz40000gp/T/ipykernel_32335/924247162.py:6: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ).groupby(['model_name'], as_index=False, sort=False).apply(lambda x: x.loc[x["Mean"].idxmax(), :])

                         Model     Variant      Mean       Std
0                 Llama-3.2-1B     Options  0.283329  0.048375
1        Llama-3.2-1B-Instruct  Options F.  0.317063  0.039822
2                 Llama-3.2-3B   agreement  0.171981  0.031809
3        Llama-3.2-3B-Instruct  Options F.  0.219421  0.073405
4                 Llama-3.1-8B  Options F.  0.151213  0.035114
5        Llama-3.1-8B-Instruct  Options F.  0.175645  0.066747
6                Llama-3.1-70B     Options  0.087815  0.040088
7       Llama-3.3-70B-Instruct    Negation  0.335640  0.168559
8                  gpt2-medium   agreement  0.163992  0.013914
9               OLMo-2-1124-7B  Options F.  0.230574  0.068302
10     OLMo-2-1124-7B-Instruct  Options F.  0.451817  0.203476
11  Ministral-8B-Instruct-2410     Options  0.164534  0.043486
12                    gemma-7b  Options F.  0.078834  0.045596
13                 gemma-7b-it     Options  0.779220  0.039983
14                openai-gpt-4    Negation  0.306519  0.287204